### ISSUE TITLE
Add to HLint README

### ISSUE THREAD

**Issue by ndmitchell** [tfausak/splint#1]
Happy to add this to the HLint readme once it's up on Hackage. Just let me know.

**Comment by tfausak** [comment]
Ah, good timing! I just published [splint-1.0.0.0](https://hackage.haskell.org/package/splint-1.0.0.0) to Hackage.

**Comment by ndmitchell** [comment]
Added in https://github.com/ndmitchell/hlint/commit/ef5cd6e69a9d4563c903746aed8be69a80a4ca63

**Comment by tfausak** [comment]
Awesome, thank you!
