### ISSUE TITLE
hlint 3.3 / GHC 9 support

### ISSUE THREAD

**Issue by bergmark** [tfausak/splint#7]
```
hlint-3.3 ([changelog](http://hackage.haskell.org/package/hlint-3.3/changelog)) (Neil Mitchell <ndmitchell@gmail.com> @ndmitchell) is out of bounds for:
-  splint-1.0.1.3 (>=3.1.6 && < 3.3). Taylor Fausak <taylor@fausak.me> @tfausak. @tfausak. Used by: library
```
Filing this here as stackage is not on GHC 9 yet.

**Comment by tfausak** [comment]
Thanks for the report! This should be a simple version bump, but it'll take me a minute to actually build it and test it out.

**Comment by tfausak** [comment]
Looks like I messed up in c908d9a112f6c48f61d08b1fef8f08598114dea4 because Splint doesn't actually work with GHC 9.0. The new module hierarchy messes up my imports. Will fix!
